# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='signal.proto',
  package='signal.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csignal.proto\x12\tsignal.v1\"\xff\x02\n\x06Signal\x12*\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x19.signal.v1.Signal.Command\x12+\n\x04type\x18\x02 \x01(\x0e\x32\x1d.signal.v1.Signal.CommandType\x1a\x1c\n\x0b\x43ommandData\x12\r\n\x05value\x18\x01 \x01(\t\"\xa4\x01\n\x07\x43ommand\x12\x17\n\x13\x43OMMAND_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x43OMMAND_VERSION\x10\x01\x12\x14\n\x10\x43OMMAND_LOCATION\x10\x02\x12\x13\n\x0f\x43OMMAND_BATTERY\x10\x03\x12\x13\n\x0f\x43OMMAND_PIN_MAP\x10\x04\x12\x15\n\x11\x43OMMAND_PIN_STATE\x10\x05\x12\x14\n\x10\x43OMMAND_PIN_MODE\x10\x06\"W\n\x0b\x43ommandType\x12\x1c\n\x18\x43OMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x43OMMAND_TYPE_GET\x10\x01\x12\x14\n\x10\x43OMMAND_TYPE_SET\x10\x02\x62\x06proto3'
)



_SIGNAL_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='signal.v1.Signal.Command',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMMAND_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_VERSION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_LOCATION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_BATTERY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_PIN_MAP', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_PIN_STATE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_PIN_MODE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=158,
  serialized_end=322,
)
_sym_db.RegisterEnumDescriptor(_SIGNAL_COMMAND)

_SIGNAL_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='signal.v1.Signal.CommandType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_GET', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_SET', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=324,
  serialized_end=411,
)
_sym_db.RegisterEnumDescriptor(_SIGNAL_COMMANDTYPE)


_SIGNAL_COMMANDDATA = _descriptor.Descriptor(
  name='CommandData',
  full_name='signal.v1.Signal.CommandData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='signal.v1.Signal.CommandData.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=155,
)

_SIGNAL = _descriptor.Descriptor(
  name='Signal',
  full_name='signal.v1.Signal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='signal.v1.Signal.command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='signal.v1.Signal.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SIGNAL_COMMANDDATA, ],
  enum_types=[
    _SIGNAL_COMMAND,
    _SIGNAL_COMMANDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=411,
)

_SIGNAL_COMMANDDATA.containing_type = _SIGNAL
_SIGNAL.fields_by_name['command'].enum_type = _SIGNAL_COMMAND
_SIGNAL.fields_by_name['type'].enum_type = _SIGNAL_COMMANDTYPE
_SIGNAL_COMMAND.containing_type = _SIGNAL
_SIGNAL_COMMANDTYPE.containing_type = _SIGNAL
DESCRIPTOR.message_types_by_name['Signal'] = _SIGNAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Signal = _reflection.GeneratedProtocolMessageType('Signal', (_message.Message,), {

  'CommandData' : _reflection.GeneratedProtocolMessageType('CommandData', (_message.Message,), {
    'DESCRIPTOR' : _SIGNAL_COMMANDDATA,
    '__module__' : 'signal_pb2'
    # @@protoc_insertion_point(class_scope:signal.v1.Signal.CommandData)
    })
  ,
  'DESCRIPTOR' : _SIGNAL,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.v1.Signal)
  })
_sym_db.RegisterMessage(Signal)
_sym_db.RegisterMessage(Signal.CommandData)


# @@protoc_insertion_point(module_scope)
