# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pixel/v1/pixel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pixel/v1/pixel.proto',
  package='pixel.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14pixel/v1/pixel.proto\x12\x08pixel.v1\"\xa0\x02\n\x05Pixel\x12\x11\n\tpixel_pin\x18\x01 \x01(\x05\x12-\n\npixel_type\x18\x02 \x01(\x0e\x32\x19.pixel.v1.Pixel.PixelType\x12-\n\npixel_data\x18\x03 \x01(\x0b\x32\x19.pixel.v1.Pixel.PixelData\x12\x13\n\x0bpixelbuf_sz\x18\x04 \x01(\x05\x1a:\n\tPixelData\x12\x10\n\x08\x62yte_idx\x18\x01 \x01(\r\x12\r\n\x05\x66lags\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\t\"U\n\tPixelType\x12\x1a\n\x16PIXEL_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11PIXEL_TYPE_WS2812\x10\x01\x12\x15\n\x11PIXEL_TYPE_APA201\x10\x02\x62\x06proto3'
)



_PIXEL_PIXELTYPE = _descriptor.EnumDescriptor(
  name='PixelType',
  full_name='pixel.v1.Pixel.PixelType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PIXEL_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PIXEL_TYPE_WS2812', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PIXEL_TYPE_APA201', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=238,
  serialized_end=323,
)
_sym_db.RegisterEnumDescriptor(_PIXEL_PIXELTYPE)


_PIXEL_PIXELDATA = _descriptor.Descriptor(
  name='PixelData',
  full_name='pixel.v1.Pixel.PixelData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='byte_idx', full_name='pixel.v1.Pixel.PixelData.byte_idx', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flags', full_name='pixel.v1.Pixel.PixelData.flags', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='pixel.v1.Pixel.PixelData.data', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=236,
)

_PIXEL = _descriptor.Descriptor(
  name='Pixel',
  full_name='pixel.v1.Pixel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pixel_pin', full_name='pixel.v1.Pixel.pixel_pin', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pixel_type', full_name='pixel.v1.Pixel.pixel_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pixel_data', full_name='pixel.v1.Pixel.pixel_data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pixelbuf_sz', full_name='pixel.v1.Pixel.pixelbuf_sz', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PIXEL_PIXELDATA, ],
  enum_types=[
    _PIXEL_PIXELTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=323,
)

_PIXEL_PIXELDATA.containing_type = _PIXEL
_PIXEL.fields_by_name['pixel_type'].enum_type = _PIXEL_PIXELTYPE
_PIXEL.fields_by_name['pixel_data'].message_type = _PIXEL_PIXELDATA
_PIXEL_PIXELTYPE.containing_type = _PIXEL
DESCRIPTOR.message_types_by_name['Pixel'] = _PIXEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pixel = _reflection.GeneratedProtocolMessageType('Pixel', (_message.Message,), {

  'PixelData' : _reflection.GeneratedProtocolMessageType('PixelData', (_message.Message,), {
    'DESCRIPTOR' : _PIXEL_PIXELDATA,
    '__module__' : 'pixel.v1.pixel_pb2'
    # @@protoc_insertion_point(class_scope:pixel.v1.Pixel.PixelData)
    })
  ,
  'DESCRIPTOR' : _PIXEL,
  '__module__' : 'pixel.v1.pixel_pb2'
  # @@protoc_insertion_point(class_scope:pixel.v1.Pixel)
  })
_sym_db.RegisterMessage(Pixel)
_sym_db.RegisterMessage(Pixel.PixelData)


# @@protoc_insertion_point(module_scope)
