# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal/v1/signal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from semver.v1 import semver_pb2 as semver_dot_v1_dot_semver__pb2
from pin.v1 import pin_pb2 as pin_dot_v1_dot_pin__pb2
from pwm.v1 import pwm_pb2 as pwm_dot_v1_dot_pwm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='signal/v1/signal.proto',
  package='signal.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16signal/v1/signal.proto\x12\tsignal.v1\x1a\x16semver/v1/semver.proto\x1a\x10pin/v1/pin.proto\x1a\x10pwm/v1/pwm.proto\"\xa4\x04\n\x06Signal\x12*\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x19.signal.v1.Signal.Command\x1a\xb4\x01\n\x07\x43ommand\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.signal.v1.Signal.CmdType\x12\'\n\x04name\x18\x02 \x01(\x0e\x32\x19.signal.v1.Signal.CmdName\x12\x18\n\x03pin\x18\x03 \x01(\x0b\x32\x0b.pin.v1.Pin\x12#\n\x07version\x18\x04 \x01(\x0b\x32\x12.semver.v1.Version\x12\x18\n\x03pwm\x18\x05 \x01(\x0b\x32\x0b.pwm.v1.PWM\"G\n\x07\x43mdType\x12\x18\n\x14\x43MD_TYPE_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x43MD_TYPE_GET\x10\x01\x12\x10\n\x0c\x43MD_TYPE_SET\x10\x02\"\xed\x01\n\x07\x43mdName\x12\x18\n\x14\x43MD_NAME_UNSPECIFIED\x10\x00\x12\x14\n\x10\x43MD_NAME_VERSION\x10\x01\x12\x15\n\x11\x43MD_NAME_LOCATION\x10\x02\x12\x14\n\x10\x43MD_NAME_BATTERY\x10\x03\x12\x1d\n\x19\x43MD_NAME_LIST_PINS_ANALOG\x10\x04\x12\x1e\n\x1a\x43MD_NAME_LIST_PINS_DIGITAL\x10\x05\x12\x16\n\x12\x43MD_NAME_PIN_VALUE\x10\x06\x12\x15\n\x11\x43MD_NAME_PIN_MODE\x10\x07\x12\x17\n\x13\x43MD_NAME_PWM_OUTPUT\x10\x08\x62\x06proto3'
  ,
  dependencies=[semver_dot_v1_dot_semver__pb2.DESCRIPTOR,pin_dot_v1_dot_pin__pb2.DESCRIPTOR,pwm_dot_v1_dot_pwm__pb2.DESCRIPTOR,])



_SIGNAL_CMDTYPE = _descriptor.EnumDescriptor(
  name='CmdType',
  full_name='signal.v1.Signal.CmdType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_TYPE_GET', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_TYPE_SET', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=335,
  serialized_end=406,
)
_sym_db.RegisterEnumDescriptor(_SIGNAL_CMDTYPE)

_SIGNAL_CMDNAME = _descriptor.EnumDescriptor(
  name='CmdName',
  full_name='signal.v1.Signal.CmdName',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_NAME_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_NAME_VERSION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_NAME_LOCATION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_NAME_BATTERY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_NAME_LIST_PINS_ANALOG', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_NAME_LIST_PINS_DIGITAL', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_NAME_PIN_VALUE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_NAME_PIN_MODE', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_NAME_PWM_OUTPUT', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=409,
  serialized_end=646,
)
_sym_db.RegisterEnumDescriptor(_SIGNAL_CMDNAME)


_SIGNAL_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='signal.v1.Signal.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='signal.v1.Signal.Command.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='signal.v1.Signal.Command.name', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pin', full_name='signal.v1.Signal.Command.pin', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='signal.v1.Signal.Command.version', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pwm', full_name='signal.v1.Signal.Command.pwm', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=333,
)

_SIGNAL = _descriptor.Descriptor(
  name='Signal',
  full_name='signal.v1.Signal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='signal.v1.Signal.command', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SIGNAL_COMMAND, ],
  enum_types=[
    _SIGNAL_CMDTYPE,
    _SIGNAL_CMDNAME,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=646,
)

_SIGNAL_COMMAND.fields_by_name['type'].enum_type = _SIGNAL_CMDTYPE
_SIGNAL_COMMAND.fields_by_name['name'].enum_type = _SIGNAL_CMDNAME
_SIGNAL_COMMAND.fields_by_name['pin'].message_type = pin_dot_v1_dot_pin__pb2._PIN
_SIGNAL_COMMAND.fields_by_name['version'].message_type = semver_dot_v1_dot_semver__pb2._VERSION
_SIGNAL_COMMAND.fields_by_name['pwm'].message_type = pwm_dot_v1_dot_pwm__pb2._PWM
_SIGNAL_COMMAND.containing_type = _SIGNAL
_SIGNAL.fields_by_name['command'].message_type = _SIGNAL_COMMAND
_SIGNAL_CMDTYPE.containing_type = _SIGNAL
_SIGNAL_CMDNAME.containing_type = _SIGNAL
DESCRIPTOR.message_types_by_name['Signal'] = _SIGNAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Signal = _reflection.GeneratedProtocolMessageType('Signal', (_message.Message,), {

  'Command' : _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
    'DESCRIPTOR' : _SIGNAL_COMMAND,
    '__module__' : 'signal.v1.signal_pb2'
    # @@protoc_insertion_point(class_scope:signal.v1.Signal.Command)
    })
  ,
  'DESCRIPTOR' : _SIGNAL,
  '__module__' : 'signal.v1.signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.v1.Signal)
  })
_sym_db.RegisterMessage(Signal)
_sym_db.RegisterMessage(Signal.Command)


# @@protoc_insertion_point(module_scope)
