# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal/v1/signal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sensor.v1 import sensor_pb2 as sensor_dot_v1_dot_sensor__pb2
from pin.v1 import pin_pb2 as pin_dot_v1_dot_pin__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='signal/v1/signal.proto',
  package='signal.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16signal/v1/signal.proto\x12\tsignal.v1\x1a\x16sensor/v1/sensor.proto\x1a\x10pin/v1/pin.proto\"\xb4\x03\n\x13\x43reateSignalRequest\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32&.signal.v1.CreateSignalRequest.CmdType\x12\x44\n\npin_config\x18\x02 \x01(\x0b\x32..pin.v1.CreateOrUpdatePinRequest.ConfigurationH\x00\x12;\n\tpin_event\x18\x03 \x01(\x0b\x32&.pin.v1.CreateOrUpdatePinRequest.EventH\x00\x12/\n\rsensor_config\x18\x04 \x01(\x0b\x32\x16.sensor.v1.Sensor.TypeH\x00\x12/\n\x0csensor_event\x18\x05 \x01(\x0b\x32\x17.sensor.v1.Sensor.EventH\x00\"w\n\x07\x43mdType\x12\x18\n\x14\x43MD_TYPE_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x43MD_TYPE_PIN\x10\x01\x12\x17\n\x13\x43MD_TYPE_PWM_OUTPUT\x10\x02\x12\x13\n\x0f\x43MD_TYPE_SENSOR\x10\x03\x12\x12\n\x0e\x43MD_TYPE_PIXEL\x10\x04\x42\t\n\x07\x63ommand\"Y\n\x14\x43reateSignalResponse\x12\x35\n\x08pin_resp\x18\x01 \x01(\x0b\x32!.pin.v1.CreateOrUpdatePinResponseH\x00\x42\n\n\x08responseb\x06proto3'
  ,
  dependencies=[sensor_dot_v1_dot_sensor__pb2.DESCRIPTOR,pin_dot_v1_dot_pin__pb2.DESCRIPTOR,])



_CREATESIGNALREQUEST_CMDTYPE = _descriptor.EnumDescriptor(
  name='CmdType',
  full_name='signal.v1.CreateSignalRequest.CmdType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_TYPE_PIN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_TYPE_PWM_OUTPUT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_TYPE_SENSOR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_TYPE_PIXEL', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=386,
  serialized_end=505,
)
_sym_db.RegisterEnumDescriptor(_CREATESIGNALREQUEST_CMDTYPE)


_CREATESIGNALREQUEST = _descriptor.Descriptor(
  name='CreateSignalRequest',
  full_name='signal.v1.CreateSignalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='signal.v1.CreateSignalRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pin_config', full_name='signal.v1.CreateSignalRequest.pin_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pin_event', full_name='signal.v1.CreateSignalRequest.pin_event', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_config', full_name='signal.v1.CreateSignalRequest.sensor_config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_event', full_name='signal.v1.CreateSignalRequest.sensor_event', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CREATESIGNALREQUEST_CMDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command', full_name='signal.v1.CreateSignalRequest.command',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=80,
  serialized_end=516,
)


_CREATESIGNALRESPONSE = _descriptor.Descriptor(
  name='CreateSignalResponse',
  full_name='signal.v1.CreateSignalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pin_resp', full_name='signal.v1.CreateSignalResponse.pin_resp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='signal.v1.CreateSignalResponse.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=518,
  serialized_end=607,
)

_CREATESIGNALREQUEST.fields_by_name['type'].enum_type = _CREATESIGNALREQUEST_CMDTYPE
_CREATESIGNALREQUEST.fields_by_name['pin_config'].message_type = pin_dot_v1_dot_pin__pb2._CREATEORUPDATEPINREQUEST_CONFIGURATION
_CREATESIGNALREQUEST.fields_by_name['pin_event'].message_type = pin_dot_v1_dot_pin__pb2._CREATEORUPDATEPINREQUEST_EVENT
_CREATESIGNALREQUEST.fields_by_name['sensor_config'].message_type = sensor_dot_v1_dot_sensor__pb2._SENSOR_TYPE
_CREATESIGNALREQUEST.fields_by_name['sensor_event'].message_type = sensor_dot_v1_dot_sensor__pb2._SENSOR_EVENT
_CREATESIGNALREQUEST_CMDTYPE.containing_type = _CREATESIGNALREQUEST
_CREATESIGNALREQUEST.oneofs_by_name['command'].fields.append(
  _CREATESIGNALREQUEST.fields_by_name['pin_config'])
_CREATESIGNALREQUEST.fields_by_name['pin_config'].containing_oneof = _CREATESIGNALREQUEST.oneofs_by_name['command']
_CREATESIGNALREQUEST.oneofs_by_name['command'].fields.append(
  _CREATESIGNALREQUEST.fields_by_name['pin_event'])
_CREATESIGNALREQUEST.fields_by_name['pin_event'].containing_oneof = _CREATESIGNALREQUEST.oneofs_by_name['command']
_CREATESIGNALREQUEST.oneofs_by_name['command'].fields.append(
  _CREATESIGNALREQUEST.fields_by_name['sensor_config'])
_CREATESIGNALREQUEST.fields_by_name['sensor_config'].containing_oneof = _CREATESIGNALREQUEST.oneofs_by_name['command']
_CREATESIGNALREQUEST.oneofs_by_name['command'].fields.append(
  _CREATESIGNALREQUEST.fields_by_name['sensor_event'])
_CREATESIGNALREQUEST.fields_by_name['sensor_event'].containing_oneof = _CREATESIGNALREQUEST.oneofs_by_name['command']
_CREATESIGNALRESPONSE.fields_by_name['pin_resp'].message_type = pin_dot_v1_dot_pin__pb2._CREATEORUPDATEPINRESPONSE
_CREATESIGNALRESPONSE.oneofs_by_name['response'].fields.append(
  _CREATESIGNALRESPONSE.fields_by_name['pin_resp'])
_CREATESIGNALRESPONSE.fields_by_name['pin_resp'].containing_oneof = _CREATESIGNALRESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['CreateSignalRequest'] = _CREATESIGNALREQUEST
DESCRIPTOR.message_types_by_name['CreateSignalResponse'] = _CREATESIGNALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateSignalRequest = _reflection.GeneratedProtocolMessageType('CreateSignalRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESIGNALREQUEST,
  '__module__' : 'signal.v1.signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.v1.CreateSignalRequest)
  })
_sym_db.RegisterMessage(CreateSignalRequest)

CreateSignalResponse = _reflection.GeneratedProtocolMessageType('CreateSignalResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATESIGNALRESPONSE,
  '__module__' : 'signal.v1.signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.v1.CreateSignalResponse)
  })
_sym_db.RegisterMessage(CreateSignalResponse)


# @@protoc_insertion_point(module_scope)
