// SPDX-FileCopyrightText: 2023-2026 Brent Rubell, Loren Norman, Tyeth Gundry for Adafruit Industries
// SPDX-License-Identifier: MIT
syntax = "proto3";
package ws.analogin;
import "sensor.proto";

/**
 * BrokerToDevice message envelope
 */
message B2D {
  oneof payload {
    Add add       = 1;
    Remove remove = 2;
  }
}

/**
 * DeviceToBroker message envelope
 */
message D2B {
  oneof payload {
    Event event = 1;
  }
}

/**
* SampleMode specifies the pin's sample mode.
*/
enum SampleMode {
  SM_UNSPECIFIED = 0; /** Invalid Sample Mode from Broker. */
  SM_TIMER       = 1; /** Periodically sample the pin's value. */
  SM_EVENT       = 2; /** Sample the pin's value when an event occurs. */
}

/**
* Gain specifies the pin's ADC gain setting.
*/
enum Gain {
  G_UNSPECIFIED = 0; /** Use platform default gain. */
  G_1X          = 1; /** No gain, or unity gain. */
  G_2X          = 2; /** Gain of 2x */
  G_2_3X        = 3; /** Gain of 2/3x (Utilized by ADS1x15) */
  G_4X          = 4; /** Gain of 4x */
  G_8X          = 5; /** Gain of 8x */
  G_16X         = 6; /** Gain of 16x */
  G_32X         = 7; /** Gain of 32x */
  G_64X         = 8; /** Gain of 64x */
  G_128X        = 9; /** Gain of 128x */
}

/**
* Add adds an analog input pin to the device.
*/
message Add {
  string pin_name          = 1; /** Name of the pin. */
  float period             = 2; /** Time between reads, in seconds. */
  ws.sensor.Type read_mode = 3; /** Desired read mode for the pin. */
  SampleMode sample_mode   = 4; /** Desired sample mode for the pin. */
  float ref_voltage        = 5; /** Reference voltage for the pin, in volts. */
  Gain gain                = 6; /** Optional ADC gain setting. */
}

/**
* Remove removes an analog input pin from the device.
*/
message Remove {
  string pin_name = 1; /** Name of the pin. */
}

/**
* Event contains a value, sent when an analog input pin is read.
*/
message Event {
  string pin_name       = 1; /** Name of the pin. */
  ws.sensor.Event value = 2; /** Reading(s) from an analog input pin. */
}
