// SPDX-FileCopyrightText: 2020-2024 Brent Rubell for Adafruit Industries
// SPDX-License-Identifier: MIT
// Messages for registering new and existing hardware with the Adafruit.io MQTT Broker
syntax = "proto3";
package wippersnapper.checkin;
import "analogio.proto";
import "digitalio.proto";
import "ds18x20.proto";
import "i2c.proto";
import "pixels.proto";
import "pwm.proto";
import "servo.proto";
import "uart.proto";

/**
 * BrokerToDevice message envelope
 */
message CheckinB2D {
  oneof payload {
    CheckinResponse checkin_response = 10;
  }
}

/**
 * DeviceToBroker message envelope
 */
message CheckinD2B {
  oneof payload {
    CheckinRequest checkin_request   = 1;
    CheckinComplete checkin_complete = 2;
  }
}

/**
* CheckinRequest notifies the MQTT broker that a new/existing device is requesting to connect.
*/
message CheckinRequest {
  string hardware_uid = 1; /** Identifies the client's physical hardware (board name + last 3 of NIC's MAC address). */
  string firmware_version = 2; /** Identifies the client's firmware version. */
}

/**
* CheckinResponse sends a broker response to the client's CheckinRequest.
*/
message CheckinResponse {
  Response response        = 1; /** Specifies if the hardware definition exists on the server. */
  int32 total_gpio_pins    = 2; /** Specifies the number of GPIO pins on the device. */
  int32 total_analog_pins  = 3; /** Specifies the number of analog pins on the device. */
  float reference_voltage  = 4; /** Specifies the hardware's default reference voltage. */

  repeated ComponentAdd component_adds = 5; /** A list of components to set up and initialize during checkin */

  /**
   * Response. Specifies if the hardware definiton is within the database.
   */
  enum Response {
    RESPONSE_UNSPECIFIED     = 0; /** Invalid response from server */
    RESPONSE_OK              = 1; /** Board found within definition index */
    RESPONSE_BOARD_NOT_FOUND = 2; /** Board not found in definition index */
  }
}

/**
 * Generic component add message, could contain any *Add message from component protos
 */
message ComponentAdd {
  oneof payload {
    wippersnapper.digitalio.DigitalIOAdd digitalio = 1;
    wippersnapper.analogio.AnalogIOAdd analogio    = 2;
    wippersnapper.servo.ServoAdd servo             = 3;
    wippersnapper.pwm.PWMAdd pwm                   = 4;
    wippersnapper.pixels.PixelsAdd pixels          = 5;
    wippersnapper.ds18x20.Ds18x20Add ds18x20       = 6;
    wippersnapper.uart.UartAdd uart                = 7;
    wippersnapper.i2c.I2cDeviceAddOrReplace i2c    = 8;
  }
}

/**
 * Signal to the broker that the device has completed the checkin
 * routine and is now operating normally
 */
message CheckinComplete {

}
