// SPDX-FileCopyrightText: 2024 Brent Rubell, Loren Norman, Tyeth Gundry for Adafruit Industries
// SPDX-License-Identifier: MIT
syntax = "proto3";
package ws.digitalio;
import "sensor.proto";

/**
 * BrokerToDevice message envelope
 */
message B2D {
  oneof payload {
    Add add       = 1;
    Remove remove = 2;
    Write write   = 3;
  }
}

/**
 * DeviceToBroker message envelope
 */
message D2B {
  oneof payload {
    Event event = 1;
  }
}

/**
* SampleMode specifies the pin's sample mode.
*/
enum SampleMode {
  SM_UNSPECIFIED = 0; /** Invalid Sample Mode from Broker. */
  SM_TIMER       = 1; /** Periodically sample the pin's value. */
  SM_EVENT       = 2; /** Sample the pin's value when an event occurs. */
}

/**
* Direction specifies the pin's direction, INPUT/INPUT_PULL_UP/OUTPUT.
*/
enum Direction {
  D_UNSPECIFIED   = 0; /** Invalid Direction from Broker. */
  D_INPUT         = 1; /** Set the pin to behave as an input. */
  D_INPUT_PULL_UP = 2; /** Set the pin to behave as an input. */
  D_OUTPUT        = 3; /** Set the pin to behave as an output. */
}

/**
* Add adds a digital pin to the device.
*/
message Add {
  string pin_name          = 1; /** The pin's name. */
  Direction gpio_direction = 2; /** The pin's direction. */
  SampleMode sample_mode   = 3; /** Specifies the pin's sample mode. */
  float period             = 4; /** Time between measurements in seconds, if MODE_TIMER. */
  Write write              = 5; /** Optional initial value to write to the pin, used during check-in. */
}

/**
* Remove removes a digital pin from the device.
*/
message Remove {
  string pin_name = 1; /** The pin's name. */
}

/**
* Event is sent from the device to the broker when a digital pin's value changes.
*/
message Event {
  string pin_name       = 1; /** The pin's name. */
  ws.sensor.Event value = 2; /** The pin's value. */
}

/**
* Write writes a boolean value to a digital pin.
*/
message Write {
  string pin_name       = 1; /** The pin's name. */
  ws.sensor.Event value = 2; /** The pin's value. */
}
