// SPDX-FileCopyrightText: 2025 Brent Rubell, Loren Norman, Tyeth Gundry for Adafruit Industries
// SPDX-License-Identifier: MIT
syntax = "proto3";
package ws.error;
import "i2c.proto";
import "uart.proto";

/*
 * B2D
 * The B2D message is sent from the broker to a device
 * to inform the device of an error that has occurred
 * from IO.
 */
message B2D {
  oneof payload {
    BanError      ban      = 1;
    ThrottleError throttle = 2;
  }
}

/*
 * D2B
 * The D2B message is sent from a device to the broker
 * to report an error that has occurred on a specific component.
 * It contains a way to identify the specific component along
 * with a human-readable error message.
 */
message D2B {
  oneof payload {
    DeviceError device       = 1;
    ComponentError component = 2;
  }
}

/*
 * BanError
 * The BanError message is sent from the broker to a device
 * to inform the device that it has been banned from IO.
 */
message BanError {

}

/*
 * ThrottleError
 * The ThrottleError message is sent from the broker to a device
 * to inform the device that it has been rate-limited by IO.
 */
message ThrottleError {
  uint32 timeout = 1;
}

/*
 * DeviceError represents a device-level issue
 */
message DeviceError {

}

/*
 * ComopnentError represents a specific error about a specfici components.
 */
message ComponentError {

}
