// SPDX-FileCopyrightText: 2026 Brent Rubell for Adafruit Industries
// SPDX-License-Identifier: MIT
syntax = "proto3";
package ws.expander;
import "i2c.proto";

/**
 * BrokerToDevice message envelope
 */
message B2D {
  oneof payload {
    Add add       = 1;
    Remove remove = 2;
  }
}

/**
 DeviceToBroker message envelope
 */
message D2B {
  oneof payload {
    Added added     = 1;
    Removed removed = 2;
  }
}

/**
* Add adds an expander to the hardware.
*/
message Add {
  i2c.DeviceAddOrReplace cfg_i2c = 1; /** I2C configuration for the expander. */
}

/**
* Added represents a message from the hardware indicating an expander was added.
*/
message Added {
  i2c.DeviceAddedOrReplaced response_i2c = 1; /** I2C configuration response. */
}

/**
* Remove removes an analog pin from the hardware.
*/
message Remove {
  i2c.DeviceRemove cfg_i2c = 1; /** I2C configuration for the expander to remove. */
}

/**
* Removed represents a message from the device indicating an expander was removed.
*/
message Removed {
  i2c.DeviceRemoved response_i2c = 1; /** I2C configuration response. */
}
