// SPDX-FileCopyrightText: 2026 Brent Rubell for Adafruit Industries
// SPDX-License-Identifier: MIT
syntax = "proto3";
package ws.expander;
import "i2c.proto";

/**
 * BrokerToDevice message envelope
 */
message B2D {
  oneof payload {
    Add add       = 1;
    Remove remove = 2;
    Modify modify = 3;
  }
}

/**
* Add adds an expander to the hardware.
*/
message Add {
  i2c.Add cfg_i2c = 1; /** I2C configuration for the expander. */
}

/**
* Remove removes an expander from the hardware.
*/
message Remove {
  i2c.Remove cfg_i2c = 1; /** I2C configuration for the expander to remove. */
}

/**
 * A combined Remove/Add message, for when a user updates an existing component. Allows the user to change
 * deep settings and keeps protobuf traffic to a single message.
 */
message Modify {
  Remove remove = 1; /** Specifies the old component/settings to remove */
  Add add       = 2; /** Specifies the new component/settings to configure after removal */
}
