// SPDX-FileCopyrightText: 2021-2024 Brent Rubell for Adafruit Industries
// SPDX-License-Identifier: MIT
// Shared I2C type definitions used by both i2c.proto and display.proto
// Extracted to break circular dependency.
syntax = "proto3";
package ws.i2c;

/**
* DeviceDescriptor represents the I2c device's address and related metadata.
*/
message DeviceDescriptor {
  string bus_sda        = 1; /** Optional SDA pin for an alt. i2c bus.**/
  string bus_scl        = 2; /** Optional SCL pin for an alt. i2c bus.**/
  uint32 device_address = 3; /** I2C Device's Address. **/
  uint32 mux_address    = 4; /** Optional I2C multiplexer address. **/
  uint32 mux_channel    = 5; /** Optional I2C multiplexer channel. **/
}

/**
* BusDescriptor represents the I2c bus' SDA and SCL pins.
*/
message BusDescriptor {
  string bus_sda = 1; /** SDA pin for an i2c bus.**/
  string bus_scl = 2; /** SCL pin for an i2c bus.**/
}
