// SPDX-FileCopyrightText: 2020-2025 Brent Rubell, Loren Norman for Adafruit Industries
// SPDX-License-Identifier: MIT
syntax = "proto3";
package ws.signal;
import "error.proto";
import "checkin.proto";
import "analogio.proto";
import "digitalio.proto";
import "display.proto";
import "ds18x20.proto";
import "i2c.proto";
import "pixels.proto";
import "pwm.proto";
import "servo.proto";
import "sleep.proto";
import "uart.proto";
import "gps.proto";

/*
 * BrokerToDevice
 * The BrokerToDevice message is sent from the broker to the device.
 * It contains a oneof payload, which is a union of all the possible
 * message-types that can be sent from the broker to a device.
 */
message BrokerToDevice {
  oneof payload {
    // System Events
    ws.error.ErrorB2D error    = 10;

    // Device Interactions
    ws.checkin.B2D checkin     = 20;
    ws.sleep.B2D sleep         = 21;

    // Component Interactions
    ws.digitalio.B2D digitalio = 30;
    ws.analogio.B2D analogio   = 31;
    ws.servo.B2D servo         = 32;
    ws.pwm.B2D pwm             = 33;
    ws.pixels.B2D pixels       = 34;
    ws.ds18x20.B2D ds18x20     = 35;
    ws.display.B2D display     = 36;
    ws.uart.B2D uart           = 37;
    ws.i2c.B2D i2c             = 38;
  }
}

/*
 * DeviceToBroker
 * The DeviceToBroker message is sent from the device to the broker.
 * It contains a oneof payload, which is a union of all the possible
 * message-types that can be sent from a device to the broker.
 */
message DeviceToBroker {
  oneof payload {
    // System Events
    ws.error.ErrorD2B error    = 10;

    // Device Interactions
    ws.checkin.D2B checkin     = 20;
    ws.sleep.D2B sleep         = 21;

    // Component Interactions
    ws.digitalio.D2B digitalio = 30;
    ws.analogio.D2B analogio   = 31;
    ws.servo.D2B servo         = 32;
    ws.pwm.D2B pwm             = 33;
    ws.pixels.D2B pixels       = 34;
    ws.display.D2B display     = 35;
    ws.uart.D2B uart           = 36;
    ws.i2c.D2B i2c             = 37;
    ws.gps.D2B gps             = 38;
  }
}
