// SPDX-FileCopyrightText: 2020-2024 Brent Rubell, Loren Norman for Adafruit Industries
// SPDX-License-Identifier: MIT
syntax = "proto3";
package wippersnapper.signal;
import "error.proto";
import "checkin.proto";
import "analogio.proto";
import "digitalio.proto";
import "ds18x20.proto";
import "i2c.proto";
import "pixels.proto";
import "pwm.proto";
import "servo.proto";
import "uart.proto";
import "gps.proto";

/*
 * BrokerToDevice
 * The BrokerToDevice message is sent from the broker to the device.
 * It contains a oneof payload, which is a union of all the possible
 * message-types that can be sent from the broker to a device.
 */
message BrokerToDevice {
  oneof payload {
    // System Events
    wippersnapper.error.ErrorB2D error = 10;

    // Device Interactions
    wippersnapper.checkin.CheckinB2D checkin = 20;

    // Component Interactions
    wippersnapper.digitalio.DigitalIOB2D digitalio = 30;
    wippersnapper.analogio.AnalogIOB2D analogio    = 31;
    wippersnapper.servo.ServoB2D servo             = 32;
    wippersnapper.pwm.PWMB2D pwm                   = 33;
    wippersnapper.pixels.PixelsB2D pixels          = 34;
    wippersnapper.ds18x20.Ds18x20B2D ds18x20       = 35;
    wippersnapper.uart.UartB2D uart                = 36;
    wippersnapper.i2c.I2cB2D i2c                   = 37;
  }
}

/*
 * DeviceToBroker
 * The DeviceToBroker message is sent from the device to the broker.
 * It contains a oneof payload, which is a union of all the possible
 * message-types that can be sent from a device to the broker.
 */
message DeviceToBroker {
  oneof payload {
    // System Events
    wippersnapper.error.ErrorD2B error = 10;

    // Device Interactions
    wippersnapper.checkin.CheckinD2B checkin = 20;

    // Component Interactions
    wippersnapper.digitalio.DigitalIOD2B digitalio = 30;
    wippersnapper.analogio.AnalogIOD2B analogio    = 31;
    wippersnapper.servo.ServoD2B servo             = 32;
    wippersnapper.pwm.PWMD2B pwm                   = 33;
    wippersnapper.pixels.PixelsD2B pixels          = 34;
    wippersnapper.ds18x20.Ds18x20D2B ds18x20       = 35;
    wippersnapper.uart.UartD2B uart                = 36;
    wippersnapper.i2c.I2cD2B i2c                   = 37;
    wippersnapper.gps.GPSD2B gps                   = 38;
  }
}
