# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pin/v1/pin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pin/v1/pin.proto',
  package='pin.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10pin/v1/pin.proto\x12\x06pin.v1\"\xca\x05\n\x18\x43reateOrUpdatePinRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12>\n\x06\x63onfig\x18\x02 \x01(\x0b\x32..pin.v1.CreateOrUpdatePinRequest.Configuration\x12\x35\n\x05\x65vent\x18\x03 \x01(\x0b\x32&.pin.v1.CreateOrUpdatePinRequest.Event\x1a\xd2\x03\n\rConfiguration\x12\x41\n\x04mode\x18\x01 \x01(\x0e\x32\x33.pin.v1.CreateOrUpdatePinRequest.Configuration.Mode\x12K\n\tdirection\x18\x02 \x01(\x0e\x32\x38.pin.v1.CreateOrUpdatePinRequest.Configuration.Direction\x12\x41\n\x04pull\x18\x03 \x01(\x0e\x32\x33.pin.v1.CreateOrUpdatePinRequest.Configuration.Pull\x12\x0e\n\x06period\x18\x04 \x01(\x05\"Q\n\x04Mode\x12\x14\n\x10MODE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bMODE_ANALOG\x10\x01\x12\x10\n\x0cMODE_DIGITAL\x10\x02\x12\x10\n\x0cMODE_PULL_UP\x10\x03\"Q\n\tDirection\x12\x19\n\x15\x44IRECTION_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x44IRECTION_INPUT\x10\x01\x12\x14\n\x10\x44IRECTION_OUTPUT\x10\x02\"8\n\x04Pull\x12\x14\n\x10PULL_UNSPECIFIED\x10\x00\x12\x0b\n\x07PULL_UP\x10\x01\x12\r\n\tPULL_DOWN\x10\x02\x1aT\n\x05\x45vent\x12\x0f\n\x05i_val\x18\x01 \x01(\x05H\x00\x12\x0f\n\x05\x62_val\x18\x02 \x01(\x08H\x00\x12\x0f\n\x05\x66_val\x18\x03 \x01(\x02H\x00\x12\x0f\n\x05s_val\x18\x04 \x01(\tH\x00\x42\x07\n\x05value\"\xea\x01\n\x19\x43reateOrUpdatePinResponse\x12?\n\x08response\x18\x01 \x01(\x0e\x32-.pin.v1.CreateOrUpdatePinResponse.PinResponse\"\x8b\x01\n\x0bPinResponse\x12\x1c\n\x18PIN_RESPONSE_UNSPECIFIED\x10\x00\x12\x1b\n\x17PIN_RESPONSE_INPUT_ONLY\x10\x01\x12\"\n\x1ePIN_RESPONSE_INVALID_DIRECTION\x10\x02\x12\x1d\n\x19PIN_RESPONSE_INVALID_PULL\x10\x03\x62\x06proto3'
)



_CREATEORUPDATEPINREQUEST_CONFIGURATION_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='pin.v1.CreateOrUpdatePinRequest.Configuration.Mode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MODE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODE_ANALOG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODE_DIGITAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODE_PULL_UP', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=435,
  serialized_end=516,
)
_sym_db.RegisterEnumDescriptor(_CREATEORUPDATEPINREQUEST_CONFIGURATION_MODE)

_CREATEORUPDATEPINREQUEST_CONFIGURATION_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='pin.v1.CreateOrUpdatePinRequest.Configuration.Direction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIRECTION_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIRECTION_INPUT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIRECTION_OUTPUT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=518,
  serialized_end=599,
)
_sym_db.RegisterEnumDescriptor(_CREATEORUPDATEPINREQUEST_CONFIGURATION_DIRECTION)

_CREATEORUPDATEPINREQUEST_CONFIGURATION_PULL = _descriptor.EnumDescriptor(
  name='Pull',
  full_name='pin.v1.CreateOrUpdatePinRequest.Configuration.Pull',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PULL_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PULL_UP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PULL_DOWN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=601,
  serialized_end=657,
)
_sym_db.RegisterEnumDescriptor(_CREATEORUPDATEPINREQUEST_CONFIGURATION_PULL)

_CREATEORUPDATEPINRESPONSE_PINRESPONSE = _descriptor.EnumDescriptor(
  name='PinResponse',
  full_name='pin.v1.CreateOrUpdatePinResponse.PinResponse',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PIN_RESPONSE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PIN_RESPONSE_INPUT_ONLY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PIN_RESPONSE_INVALID_DIRECTION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PIN_RESPONSE_INVALID_PULL', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=841,
  serialized_end=980,
)
_sym_db.RegisterEnumDescriptor(_CREATEORUPDATEPINRESPONSE_PINRESPONSE)


_CREATEORUPDATEPINREQUEST_CONFIGURATION = _descriptor.Descriptor(
  name='Configuration',
  full_name='pin.v1.CreateOrUpdatePinRequest.Configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='pin.v1.CreateOrUpdatePinRequest.Configuration.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direction', full_name='pin.v1.CreateOrUpdatePinRequest.Configuration.direction', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pull', full_name='pin.v1.CreateOrUpdatePinRequest.Configuration.pull', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='period', full_name='pin.v1.CreateOrUpdatePinRequest.Configuration.period', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CREATEORUPDATEPINREQUEST_CONFIGURATION_MODE,
    _CREATEORUPDATEPINREQUEST_CONFIGURATION_DIRECTION,
    _CREATEORUPDATEPINREQUEST_CONFIGURATION_PULL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=657,
)

_CREATEORUPDATEPINREQUEST_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='pin.v1.CreateOrUpdatePinRequest.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='i_val', full_name='pin.v1.CreateOrUpdatePinRequest.Event.i_val', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b_val', full_name='pin.v1.CreateOrUpdatePinRequest.Event.b_val', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='f_val', full_name='pin.v1.CreateOrUpdatePinRequest.Event.f_val', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s_val', full_name='pin.v1.CreateOrUpdatePinRequest.Event.s_val', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='pin.v1.CreateOrUpdatePinRequest.Event.value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=659,
  serialized_end=743,
)

_CREATEORUPDATEPINREQUEST = _descriptor.Descriptor(
  name='CreateOrUpdatePinRequest',
  full_name='pin.v1.CreateOrUpdatePinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pin.v1.CreateOrUpdatePinRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='pin.v1.CreateOrUpdatePinRequest.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event', full_name='pin.v1.CreateOrUpdatePinRequest.event', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CREATEORUPDATEPINREQUEST_CONFIGURATION, _CREATEORUPDATEPINREQUEST_EVENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=743,
)


_CREATEORUPDATEPINRESPONSE = _descriptor.Descriptor(
  name='CreateOrUpdatePinResponse',
  full_name='pin.v1.CreateOrUpdatePinResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='pin.v1.CreateOrUpdatePinResponse.response', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CREATEORUPDATEPINRESPONSE_PINRESPONSE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=746,
  serialized_end=980,
)

_CREATEORUPDATEPINREQUEST_CONFIGURATION.fields_by_name['mode'].enum_type = _CREATEORUPDATEPINREQUEST_CONFIGURATION_MODE
_CREATEORUPDATEPINREQUEST_CONFIGURATION.fields_by_name['direction'].enum_type = _CREATEORUPDATEPINREQUEST_CONFIGURATION_DIRECTION
_CREATEORUPDATEPINREQUEST_CONFIGURATION.fields_by_name['pull'].enum_type = _CREATEORUPDATEPINREQUEST_CONFIGURATION_PULL
_CREATEORUPDATEPINREQUEST_CONFIGURATION.containing_type = _CREATEORUPDATEPINREQUEST
_CREATEORUPDATEPINREQUEST_CONFIGURATION_MODE.containing_type = _CREATEORUPDATEPINREQUEST_CONFIGURATION
_CREATEORUPDATEPINREQUEST_CONFIGURATION_DIRECTION.containing_type = _CREATEORUPDATEPINREQUEST_CONFIGURATION
_CREATEORUPDATEPINREQUEST_CONFIGURATION_PULL.containing_type = _CREATEORUPDATEPINREQUEST_CONFIGURATION
_CREATEORUPDATEPINREQUEST_EVENT.containing_type = _CREATEORUPDATEPINREQUEST
_CREATEORUPDATEPINREQUEST_EVENT.oneofs_by_name['value'].fields.append(
  _CREATEORUPDATEPINREQUEST_EVENT.fields_by_name['i_val'])
_CREATEORUPDATEPINREQUEST_EVENT.fields_by_name['i_val'].containing_oneof = _CREATEORUPDATEPINREQUEST_EVENT.oneofs_by_name['value']
_CREATEORUPDATEPINREQUEST_EVENT.oneofs_by_name['value'].fields.append(
  _CREATEORUPDATEPINREQUEST_EVENT.fields_by_name['b_val'])
_CREATEORUPDATEPINREQUEST_EVENT.fields_by_name['b_val'].containing_oneof = _CREATEORUPDATEPINREQUEST_EVENT.oneofs_by_name['value']
_CREATEORUPDATEPINREQUEST_EVENT.oneofs_by_name['value'].fields.append(
  _CREATEORUPDATEPINREQUEST_EVENT.fields_by_name['f_val'])
_CREATEORUPDATEPINREQUEST_EVENT.fields_by_name['f_val'].containing_oneof = _CREATEORUPDATEPINREQUEST_EVENT.oneofs_by_name['value']
_CREATEORUPDATEPINREQUEST_EVENT.oneofs_by_name['value'].fields.append(
  _CREATEORUPDATEPINREQUEST_EVENT.fields_by_name['s_val'])
_CREATEORUPDATEPINREQUEST_EVENT.fields_by_name['s_val'].containing_oneof = _CREATEORUPDATEPINREQUEST_EVENT.oneofs_by_name['value']
_CREATEORUPDATEPINREQUEST.fields_by_name['config'].message_type = _CREATEORUPDATEPINREQUEST_CONFIGURATION
_CREATEORUPDATEPINREQUEST.fields_by_name['event'].message_type = _CREATEORUPDATEPINREQUEST_EVENT
_CREATEORUPDATEPINRESPONSE.fields_by_name['response'].enum_type = _CREATEORUPDATEPINRESPONSE_PINRESPONSE
_CREATEORUPDATEPINRESPONSE_PINRESPONSE.containing_type = _CREATEORUPDATEPINRESPONSE
DESCRIPTOR.message_types_by_name['CreateOrUpdatePinRequest'] = _CREATEORUPDATEPINREQUEST
DESCRIPTOR.message_types_by_name['CreateOrUpdatePinResponse'] = _CREATEORUPDATEPINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateOrUpdatePinRequest = _reflection.GeneratedProtocolMessageType('CreateOrUpdatePinRequest', (_message.Message,), {

  'Configuration' : _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), {
    'DESCRIPTOR' : _CREATEORUPDATEPINREQUEST_CONFIGURATION,
    '__module__' : 'pin.v1.pin_pb2'
    # @@protoc_insertion_point(class_scope:pin.v1.CreateOrUpdatePinRequest.Configuration)
    })
  ,

  'Event' : _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
    'DESCRIPTOR' : _CREATEORUPDATEPINREQUEST_EVENT,
    '__module__' : 'pin.v1.pin_pb2'
    # @@protoc_insertion_point(class_scope:pin.v1.CreateOrUpdatePinRequest.Event)
    })
  ,
  'DESCRIPTOR' : _CREATEORUPDATEPINREQUEST,
  '__module__' : 'pin.v1.pin_pb2'
  # @@protoc_insertion_point(class_scope:pin.v1.CreateOrUpdatePinRequest)
  })
_sym_db.RegisterMessage(CreateOrUpdatePinRequest)
_sym_db.RegisterMessage(CreateOrUpdatePinRequest.Configuration)
_sym_db.RegisterMessage(CreateOrUpdatePinRequest.Event)

CreateOrUpdatePinResponse = _reflection.GeneratedProtocolMessageType('CreateOrUpdatePinResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEORUPDATEPINRESPONSE,
  '__module__' : 'pin.v1.pin_pb2'
  # @@protoc_insertion_point(class_scope:pin.v1.CreateOrUpdatePinResponse)
  })
_sym_db.RegisterMessage(CreateOrUpdatePinResponse)


# @@protoc_insertion_point(module_scope)
