name: Linting and Backwards-Compatibility Checks
# on: [ push ]
  workflow_call:
    secrets:
      GH_REPO_TOKEN:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: success()
        uses: actions/checkout@v1
        with:
          ref: master
      - name: checkout-master
        if: success()
        run: git checkout master
      - name: checkout
        if: success()
        uses: actions/checkout@v1
      - name: make local
        if: success()
        run: make local
