# SPDX-FileCopyrightText: Brent Rubell for Adafruit Industries, 2022
#
# SPDX-License-Identifier: MIT
name: WipperSnapper Protocol Buffer CI (caller workflow)

on:
  pull_request:
    branches: master
    secrets:
      GH_REPO_TOKEN:
        required: true
  push:

jobs:
  lint:
    uses: brentru/Wippersnapper_Protobuf/.github/workflows/buf-checks.yml@reusable-workflow
    secrets:
      GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
  generate:
    needs: lint
    uses: brentru/Wippersnapper_Protobuf/.github/workflows/protoc-wrapper-generation.yml@reusable-workflow
    secrets:
      GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}