name: "lint protobuf"
on: pull_request

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
    - name: Self Checkout
      uses: actions/checkout@v3
      with:
          path: protobuf-checkout
          submodules: false
    - name: list file directory structure
      run: ls -R
    - name: reviewdog protolint
      uses: yoheimuta/action-protolint@v1
      with:
        workdir: 'protobuf-checkout'
        fail_on_error: true
        protolint_flags: 'lint -config_dir_path . proto/wippersnapper'
