name: "lint protobuf"
on: pull_request

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v3
      - name: run protolint
        uses: plexsystems/protolint-action@v0.7.0
        with:
            srcDirectory: ./protobuf-checkout/proto/wippersnapper/*
            configDirectory: .github/protolint.yaml