name: "lint protobuf"
on: pull_request

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v3
      - name: list file directory structure
        run: ls -R
      - name: run protolint
        uses: plexsystems/protolint-action@v0.7.0
        with:
            srcDirectory: ./proto/wippersnapper
            configDirectory: ./github/protolint.yaml